qdrant_db:
  collection_name:"document_chat"


embedding_model:
  provider:"google"
  model_name:"sentance_transformer/allMini-LM_v6"

retriever:
  top_k:5


llm:
  groq:
    provider:"groq"
    model_name: ""
    temprature: 0.2
    max_output_tokens: 2000
  
  google:
    provider:"google"
    model_name: "gemini"
    temprature: 0.2
    max_output_tokens: 2000